In [1]:
import pandas as pd

In [2]:
from glob import glob

In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/peter/Library/Python/3.11/lib/python/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install black

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: black in /Users/peter/Library/Python/3.11/lib/python/site-packages (23.7.0)
Requirement already satisfied: click>=8.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from black) (8.1.3)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from black) (1.0.0)
Requirement already satisfied: packaging>=22.0 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from black) (23.1)
Requirement already satisfied: pathspec>=0.9.0 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from black) (0.11.1)
Requirement already satisfied: platformdirs>=2 in /Users/peter/Library/Python/3.11/lib/python/site-packages (from black) (3.9.1)

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
single_file_acc = pd.read_csv(
    "../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv"
)

In [6]:
single_file_gyr = pd.read_csv(
    "../../data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv"
)

In [7]:
files = glob("../../data/raw/MetaMotion/*.csv")
len(files)

187

In [8]:
data_path = "../../data/raw/MetaMotion/"

In [9]:
f = files[1]

In [10]:
participant = f.split("-")[0].replace(data_path, "")

In [11]:
label = f.split("-")[1]

In [12]:
category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")

In [13]:
df = pd.read_csv(f)

In [14]:
df["participant"] = participant

In [15]:
df["label"] = label

In [16]:
df["category"] = category

In [17]:
acc_df = pd.DataFrame()

In [18]:
gyr_df = pd.DataFrame()

In [19]:
acc_set = 1

In [20]:
gyr_set = 1

In [21]:
for f in files:
    participant = f.split("-")[0].replace(data_path, "")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
    df = pd.read_csv(f)
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])
    if "Gyroscope" in f:
        df["set"] = gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])

In [22]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23578 entries, 0 to 169
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [23]:
pd.to_datetime(df["epoch (ms)"], unit = "ms")

0     2019-01-14 13:49:46.995
1     2019-01-14 13:49:47.075
2     2019-01-14 13:49:47.155
3     2019-01-14 13:49:47.235
4     2019-01-14 13:49:47.315
                ...
165   2019-01-14 13:50:00.195
166   2019-01-14 13:50:00.275
167   2019-01-14 13:50:00.355
168   2019-01-14 13:50:00.435
169   2019-01-14 13:50:00.515
Name: epoch (ms), Length: 170, dtype: datetime64[ns]

In [24]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit = "ms")

In [25]:
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit = "ms")

In [26]:
del acc_df["epoch (ms)"]

In [27]:
del acc_df["time (01:00)"]

In [28]:
del acc_df["elapsed (s)"]

In [29]:
del gyr_df["epoch (ms)"]

In [30]:
del gyr_df["time (01:00)"]

In [31]:
del gyr_df["elapsed (s)"]

In [32]:
files = glob("../../data/raw/MetaMotion/*.csv")

In [33]:
def read_data_from_files(files):
    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()
    acc_set = 1
    gyr_set = 1
    for f in files:
        participant = f.split("-")[0].replace(data_path, "")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("123").rstrip("_MetaWear_2019")
        df = pd.read_csv(f)
        df["participant"] = participant
        df["label"] = label
        df["category"] = category
        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])
        if "Gyroscope" in f:
            df["set"] = gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])
    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit = "ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"], unit = "ms")
    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]
    del acc_df["elapsed (s)"]
    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]
    del gyr_df["elapsed (s)"]
    return acc_df, gyr_df

In [34]:
acc_df, gyr_df = read_data_from_files(files)

In [35]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)

In [36]:
data_merged.dropna()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,2.622,-8.110,-4.024,A,bench,heavy,72.0
2019-01-11 15:10:08.511,0.000,0.961,-0.069,1.524,-2.561,-2.500,A,bench,heavy,72.0
2019-01-11 15:10:08.591,0.001,0.974,-0.087,1.707,-5.366,0.915,A,bench,heavy,72.0
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,2.683,-4.146,-1.220,A,bench,heavy,72.0
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,1.524,0.610,-3.171,A,bench,heavy,72.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-15 19:04:25.561,0.369,0.591,0.761,11.220,-5.061,-5.061,A,squat,heavy,87.0
2019-01-15 19:04:25.641,0.387,0.566,0.776,3.963,-2.988,-0.793,A,squat,heavy,87.0
2019-01-15 19:04:25.721,0.361,0.574,0.680,15.305,-3.293,-0.671,A,squat,heavy,87.0
2019-01-15 19:04:25.801,0.353,0.583,0.635,30.366,-0.122,-4.573,A,squat,heavy,87.0
2019-01-15 19:04:25.881,0.359,0.605,0.678,14.756,-6.585,-2.378,A,squat,heavy,87.0

In [37]:
data_merged.head(50)

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,64.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,64.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,64.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,64.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,64.0
2019-01-11 15:08:05.150,NaN,NaN,NaN,1.402,2.683,-4.024,B,bench,heavy,64.0
2019-01-11 15:08:05.190,NaN,NaN,NaN,-11.280,4.512,-0.671,B,bench,heavy,64.0
2019-01-11 15:08:05.230,NaN,NaN,NaN,-6.159,10.854,-16.098,B,bench,heavy,64.0
2019-01-11 15:08:05.270,NaN,NaN,NaN,1.280,-7.866,7.073,B,bench,heavy,64.0
2019-01-11 15:08:05.310,NaN,NaN,NaN,8.171,-7.073,8.110,B,bench,heavy,64.0
2019-01-11 15:08:05.314,0.016,0.980,-0.087,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.350,NaN,NaN,NaN,-7.988,8.049,1.280,B,bench,heavy,64.0
2019-01-11 15:08:05.390,NaN,NaN,NaN,-4.756,8.232,4.329,B,bench,heavy,64.0
2019-01-11 15:08:05.394,0.011,0.974,-0.055,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.430,NaN,NaN,NaN,2.866,-3.293,-0.305,B,bench,heavy,64.0
2019-01-11 15:08:05.470,NaN,NaN,NaN,-1.402,-0.915,-0.732,B,bench,heavy,64.0
2019-01-11 15:08:05.474,-0.011,0.970,-0.086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.510,NaN,NaN,NaN,0.976,-2.500,5.427,B,bench,heavy,64.0
2019-01-11 15:08:05.550,NaN,NaN,NaN,3.415,-1.829,6.220,B,bench,heavy,64.0
2019-01-11 15:08:05.554,0.008,0.971,-0.073,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.590,NaN,NaN,NaN,-14.268,4.085,0.244,B,bench,heavy,64.0
2019-01-11 15:08:05.630,NaN,NaN,NaN,-16.951,-10.366,4.512,B,bench,heavy,64.0
2019-01-11 15:08:05.634,0.012,0.996,-0.051,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.670,NaN,NaN,NaN,-0.244,4.817,-6.524,B,bench,heavy,64.0
2019-01-11 15:08:05.710,NaN,NaN,NaN,9.268,10.000,1.707,B,bench,heavy,64.0
2019-01-11 15:08:05.714,-0.001,0.977,-0.062,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.750,NaN,NaN,NaN,14.146,-4.024,-0.122,B,bench,heavy,64.0
2019-01-11 15:08:05.790,NaN,NaN,NaN,6.585,-1.707,-6.646,B,bench,heavy,64.0
2019-01-11 15:08:05.794,-0.007,0.942,-0.080,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.830,NaN,NaN,NaN,7.805,0.061,-0.244,B,bench,heavy,64.0
2019-01-11 15:08:05.870,NaN,NaN,NaN,17.744,-13.354,-9.451,B,bench,heavy,64.0
2019-01-11 15:08:05.874,-0.018,0.955,-0.091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.910,NaN,NaN,NaN,7.012,-10.488,-4.024,B,bench,heavy,64.0
2019-01-11 15:08:05.950,NaN,NaN,NaN,1.585,4.939,-2.866,B,bench,heavy,64.0
2019-01-11 15:08:05.954,-0.030,0.959,-0.056,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:05.990,NaN,NaN,NaN,6.159,-3.780,6.220,B,bench,heavy,64.0
2019-01-11 15:08:06.030,NaN,NaN,NaN,4.695,-6.707,-2.439,B,bench,heavy,64.0
2019-01-11 15:08:06.034,-0.022,0.962,-0.117,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:06.070,NaN,NaN,NaN,-1.707,-4.817,-1.463,B,bench,heavy,64.0
2019-01-11 15:08:06.110,NaN,NaN,NaN,7.561,-1.402,-0.549,B,bench,heavy,64.0
2019-01-11 15:08:06.114,-0.032,0.942,-0.112,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:06.150,NaN,NaN,NaN,6.768,0.549,-4.878,B,bench,heavy,64.0
2019-01-11 15:08:06.190,NaN,NaN,NaN,-5.122,4.634,-8.720,B,bench,heavy,64.0
2019-01-11 15:08:06.194,-0.030,0.969,-0.116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:06.230,NaN,NaN,NaN,4.573,-3.171,-0.610,B,bench,heavy,64.0
2019-01-11 15:08:06.270,NaN,NaN,NaN,6.524,-6.890,9.634,B,bench,heavy,64.0
2019-01-11 15:08:06.274,-0.004,0.987,-0.143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 15:08:06.310,NaN,NaN,NaN,-7.744,7.439,-7.683,B,bench,heavy,64.0
2019-01-11 15:08:06.350,NaN,NaN,NaN,-9.573,16.585,-16.220,B,bench,heavy,64.0
2019-01-11 15:08:06.354,-0.048,0.943,-0.093,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
data_merged.columns = [
    "acc_x",
    "acc_y",
    "acc_z",
    "gyr_x",
    "gyr_y",
    "gyr_z",
    "participant",
    "label",
    "category",    
    "set",
]

In [39]:
numeric_columns = ["acc_x", "acc_y", "acc_z", "gyr_x", "gyr_y", "gyr_z", "set"]

In [40]:
numeric_data = data_merged[numeric_columns]

In [41]:
ms_data = numeric_data[:1000].resample(rule="200ms").mean()

In [42]:
sampling = {
    "acc_x": "mean",
    "acc_y": "mean",
    "acc_z": "mean",
    "gyr_x": "mean",
    "gyr_y": "mean",
    "gyr_z": "mean",
    "participant": "last",
    "label": "last",
    "category": "last",
    "set": "last"
}

In [43]:
data_subset = data_merged[:1000]

In [44]:
ms_data = data_subset.resample(rule="200ms", closed="right").agg(sampling)

In [45]:
print(ms_data)

                            acc_x     acc_y     acc_z    gyr_x    gyr_y  \
epoch (ms)
2019-01-11 15:08:04.800       NaN       NaN       NaN -9.69550  -1.7985
2019-01-11 15:08:05.000       NaN       NaN       NaN -2.01220  -0.4270
2019-01-11 15:08:05.200  0.013500  0.977000 -0.071000 -1.89040   2.4392
2019-01-11 15:08:05.400 -0.001500  0.970500 -0.079500 -1.68260  -0.8904
2019-01-11 15:08:05.600  0.001333  0.971667 -0.064333  2.56080  -0.2560
...                           ...       ...       ...      ...      ...
2019-01-11 15:10:21.600 -0.174000  1.092667 -0.153333 -4.96360 -16.4026
2019-01-11 15:10:21.800 -0.219500  1.402500 -0.109000 -7.52440  18.6706
2019-01-11 15:10:22.000 -0.192000  0.871667 -0.155667  2.60980   8.7070
2019-01-11 15:10:22.200 -0.227000  0.891000 -0.170000  5.39020   4.0000
2019-01-11 15:10:22.400 -0.225500  0.919500 -0.205500  6.34125   0.5795

                           gyr_z participant  label category   set
epoch (ms)
2019-01-11 15:08:04.800   4.5735           B  bench    heavy  64.0
2019-01-11 15:08:05.000  -1.6218           B  bench    heavy  64.0
2019-01-11 15:08:05.200   0.9388           B  bench    heavy  64.0
2019-01-11 15:08:05.400   2.1708           B  bench    heavy  64.0
2019-01-11 15:08:05.600  -1.4146           B  bench    heavy  64.0
...                          ...         ...    ...      ...   ...
2019-01-11 15:10:21.600  21.9026           A  bench    heavy  72.0
2019-01-11 15:10:21.800 -22.6828           A  bench    heavy  72.0
2019-01-11 15:10:22.000 -14.8658           A  bench    heavy  72.0
2019-01-11 15:10:22.200  -0.3780           A  bench    heavy  72.0
2019-01-11 15:10:22.400   9.9085           A  bench    heavy  72.0

[689 rows x 10 columns]

In [47]:
days = [g for n, g in data_merged.groupby(pd.Grouper(freq="d"))]

In [48]:
days[0]

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,64.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,64.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,64.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,64.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,64.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 16:24:55.706,NaN,NaN,NaN,-8.415,7.683,4.207,A,dead,medium,57.0
2019-01-11 16:24:55.746,NaN,NaN,NaN,-4.573,-5.732,2.744,A,dead,medium,57.0
2019-01-11 16:24:55.753,0.005,-1.022,-0.176,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-11 16:24:55.786,NaN,NaN,NaN,1.463,-12.195,-0.305,A,dead,medium,57.0
2019-01-11 16:24:55.833,-0.002,-1.026,-0.189,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
data_resampled = pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days])

In [51]:
data_resampled.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   float64
dtypes: float64(7), object(3)
memory usage: 774.2+ KB

In [52]:
data_resampled["set"] = data_resampled['set'].astype("int")